### PR TITLE
Add documentation for the Gitter-ChatBot

### LINKED ISSUE #19: Need of a documentation for the project
The documentation should contain:
    A detailed explanation of the working of the chatbot
    A getting started guide
    A contribution guide with development instructions
    Deployment instruction for Heroku Cloud

### PR DESCRIPTION
**Pull request by maayami**
Fix #19 
This PR adds documentation for the project. It contains:
- Introduction
- Detailed explanation of the working of the chatbot
- A getting started guide
- A contribution guide with development instructions
- Deployment instruction for Heroku Cloud

### CODE REVIEW

**Comment by rajitha1998** [comment]
Please add a better image with straight lines @maayami 
Screenshot from 2021-08-16 16-09-52

**Comment by maayami** [comment]
Okay

**Comment by maayami** [comment]
Sir, I forgot to add one important setup instruction, please don't merge now.

**Comment by maayami** [comment]
Now, It can be merged.

**Comment by maayami** [comment]
Screenshot from 2021-08-17 13-06-09
Screenshot from 2021-08-17 13-06-57
Screenshot from 2021-08-17 13-07-34

**Review by rajitha1998 — APPROVED** [review]

**Pull request merged**
