### PR TITLE
Structure the codebase

### LINKED ISSUE #13: Improve the structure of the complete project
The current project directory has a tree structure that includes :
image

**What can be improved?**
- The main.py file has more than 150 lines of code. Split this into subfiles.

### PR DESCRIPTION
**Pull request by maayami**
Fix #13 
I have created separate files for data extraction, response generation and for the database.
image

### CODE REVIEW

**Comment by maayami** [comment]
Now project tree looks like this:
image
**Note: ** __pycache__/ and .env are not the part of the project files.

**Review by rajitha1998 — APPROVED** [review]

**Comment by rajitha1998** [comment]
Is this branch up to date @maayami ?

**Comment by maayami** [comment]
No, it is not up to date. I have new changes regarding the code base structure.

**Comment by maayami** [comment]
Yes sir it is up-to-date now. Let's merge this PR.

**Pull request merged**
